# Safety Security and License Configuration file
# https://docs.safetycli.com/safety-2/safety-cli-2-scanner/policy-file
security:
  # A severity number between 0 and 10. Some helpful reference points: 9=ignore all vulnerabilities except CRITICAL severity. 7=ignore all vulnerabilities except CRITICAL
  ignore-cvss-severity-below: 0
  # True or False. We recommend you set this to False.
  ignore-cvss-unknown-severity: False
  # Suppress non-zero exit codes when vulnerabilities are found. Enable this in pipelines and CI/CD processes if you want to pass builds that have vulnerabilities
  continue-on-vulnerability-error: False
  # Here you can list multiple specific vulnerabilities you want to ignore (optionally for a time period)
  ignore-vulnerabilities: {}
    # <id>:
    #   reason: ''
    #   expires: ''
